"""add survey records

Revision ID: 26b89dd4c943
Revises: 4f8a2c1d7b90
Create Date: 2026-09-27 22:28:38.507388

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26b89dd4c943"
down_revision: Union[str, Sequence[str], None] = "4f8a2c1d7b90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "acquisition_case_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "parcel_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "survey_reference",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "survey_type",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "survey_method",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="PLANNED",
            nullable=False,
        ),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "conducted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "surveyor_user_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "verified_by_user_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "recorded_area_sq_m",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
        ),
        sa.Column(
            "measured_area_sq_m",
            sa.Numeric(precision=18, scale=4),
            nullable=True,
        ),
        sa.Column(
            "area_difference_sq_m",
            sa.Numeric(precision=18, scale=4),
            nullable=True,
        ),
        sa.Column(
            "area_difference_percentage",
            sa.Numeric(precision=12, scale=6),
            nullable=True,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status != 'VERIFIED') OR "
            "(verified_by_user_id IS NOT NULL AND verified_at IS NOT NULL)",
            name=op.f(
                "ck_survey_records_ck_survey_records_verified_requires_verifier"
            ),
        ),
        sa.CheckConstraint(
            "(status NOT IN "
            "('COMPLETED','REQUIRES_REVIEW','VERIFIED')) "
            "OR conducted_at IS NOT NULL",
            name=op.f(
                "ck_survey_records_ck_survey_records_completed_requires_conducted_at"
            ),
        ),
        sa.CheckConstraint(
            "status IN "
            "('PLANNED','IN_PROGRESS','COMPLETED',"
            "'REQUIRES_REVIEW','VERIFIED','CANCELLED')",
            name=op.f(
                "ck_survey_records_ck_survey_records_status"
            ),
        ),
        sa.CheckConstraint(
            "survey_method IN "
            "('FIELD_SURVEY','GNSS','TOTAL_STATION','GPS',"
            "'DIGITIZED','OTHER')",
            name=op.f(
                "ck_survey_records_ck_survey_records_survey_method"
            ),
        ),
        sa.CheckConstraint(
            "survey_type IN "
            "('PRELIMINARY','JOINT_MEASUREMENT',"
            "'BOUNDARY_VERIFICATION','RE_MEASUREMENT','OTHER')",
            name=op.f(
                "ck_survey_records_ck_survey_records_survey_type"
            ),
        ),
        sa.CheckConstraint(
            "area_difference_percentage IS NULL OR "
            "area_difference_percentage = "
            "((measured_area_sq_m - recorded_area_sq_m) "
            "/ recorded_area_sq_m) * 100",
            name=op.f(
                "ck_survey_records_ck_survey_records_area_difference_percentage"
            ),
        ),
        sa.CheckConstraint(
            "area_difference_sq_m IS NULL OR "
            "area_difference_sq_m = "
            "measured_area_sq_m - recorded_area_sq_m",
            name=op.f(
                "ck_survey_records_ck_survey_records_area_difference"
            ),
        ),
        sa.CheckConstraint(
            "measured_area_sq_m IS NULL OR "
            "measured_area_sq_m > 0",
            name=op.f(
                "ck_survey_records_ck_survey_records_measured_area_positive"
            ),
        ),
        sa.CheckConstraint(
            "recorded_area_sq_m > 0",
            name=op.f(
                "ck_survey_records_ck_survey_records_recorded_area_positive"
            ),
        ),
        sa.CheckConstraint(
            "verified_at IS NULL OR "
            "conducted_at IS NULL OR "
            "verified_at >= conducted_at",
            name=op.f(
                "ck_survey_records_ck_survey_records_verified_after_conducted"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["acquisition_case_id"],
            ["acquisition_cases.id"],
            name=op.f(
                "fk_survey_records_acquisition_case_id_acquisition_cases"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["parcels.id"],
            name=op.f(
                "fk_survey_records_parcel_id_parcels"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["surveyor_user_id"],
            ["users.id"],
            name=op.f(
                "fk_survey_records_surveyor_user_id_users"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f(
                "fk_survey_records_verified_by_user_id_users"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_survey_records"),
        ),
        sa.UniqueConstraint(
            "acquisition_case_id",
            "survey_reference",
            name="uq_survey_records_case_reference",
        ),
    )

    op.create_index(
        "ix_survey_records_case_id",
        "survey_records",
        ["acquisition_case_id"],
        unique=False,
    )

    op.create_index(
        "ix_survey_records_conducted_at",
        "survey_records",
        ["conducted_at"],
        unique=False,
    )

    op.create_index(
        "ix_survey_records_parcel_id",
        "survey_records",
        ["parcel_id"],
        unique=False,
    )

    op.create_index(
        "ix_survey_records_status",
        "survey_records",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "ix_survey_records_status",
        table_name="survey_records",
    )

    op.drop_index(
        "ix_survey_records_parcel_id",
        table_name="survey_records",
    )

    op.drop_index(
        "ix_survey_records_conducted_at",
        table_name="survey_records",
    )

    op.drop_index(
        "ix_survey_records_case_id",
        table_name="survey_records",
    )

    op.drop_table("survey_records")

    # ### end Alembic commands ###