"""Add right holder source identity

Revision ID: 36996d2150e6
Revises: 44aca6000e46
Create Date: 2026-09-26 19:23:31.746731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36996d2150e6'
down_revision: Union[str, Sequence[str], None] = '44aca6000e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('right_holders', sa.Column('source_system', sa.String(length=150), nullable=True))
    op.create_index('ix_right_holders_source_system', 'right_holders', ['source_system'], unique=False)
    op.create_unique_constraint('uq_right_holders_source_external_reference', 'right_holders', ['source_system', 'external_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_right_holders_source_external_reference', 'right_holders', type_='unique')
    op.drop_index('ix_right_holders_source_system', table_name='right_holders')
    op.drop_column('right_holders', 'source_system')
    # ### end Alembic commands ###
