"""create core land domain

Revision ID: 41ea153b2421
Revises: 69652b2e6820
Create Date: 2026-09-24 18:31:52.045106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '41ea153b2421'
down_revision: Union[str, Sequence[str], None] = '69652b2e6820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parcel_reference', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('survey_number', sa.String(length=100), nullable=False),
    sa.Column('subdivision_number', sa.String(length=100), nullable=True),
    sa.Column('recorded_area_sq_m', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('surveyed_area_sq_m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('acquired_area_sq_m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('land_category', sa.String(length=100), nullable=True),
    sa.Column('land_record_reference', sa.String(length=150), nullable=True),
    sa.Column('source_system', sa.String(length=150), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acquired_area_sq_m IS NULL OR acquired_area_sq_m > 0', name=op.f('ck_parcels_ck_parcels_acquired_area_positive')),
    sa.CheckConstraint('recorded_area_sq_m > 0', name=op.f('ck_parcels_ck_parcels_recorded_area_positive')),
    sa.CheckConstraint('surveyed_area_sq_m IS NULL OR surveyed_area_sq_m > 0', name=op.f('ck_parcels_ck_parcels_surveyed_area_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcels')),
    sa.UniqueConstraint('parcel_reference', name='uq_parcels_parcel_reference')
    )
    op.create_index('ix_parcels_location', 'parcels', ['state', 'district', 'taluka', 'village'], unique=False)
    op.create_index('ix_parcels_survey_number', 'parcels', ['survey_number'], unique=False)
    op.create_table('right_holders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holder_type', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('external_reference', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("holder_type IN ('INDIVIDUAL', 'ENTITY', 'GOVERNMENT', 'COMMUNITY', 'OTHER')", name=op.f('ck_right_holders_ck_right_holders_holder_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_right_holders'))
    )
    op.create_index('ix_right_holders_display_name', 'right_holders', ['display_name'], unique=False)
    op.create_index('ix_right_holders_external_reference', 'right_holders', ['external_reference'], unique=False)
    op.create_table('parcel_interests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('right_holder_id', sa.Uuid(), nullable=False),
    sa.Column('interest_type', sa.String(length=30), nullable=False),
    sa.Column('share_percentage', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('verification_status', sa.String(length=30), server_default='UNVERIFIED', nullable=False),
    sa.Column('record_source', sa.String(length=150), nullable=True),
    sa.Column('record_reference', sa.String(length=150), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("interest_type IN ('OWNER', 'CO_OWNER', 'TENANT', 'OCCUPIER', 'LESSEE', 'OTHER')", name=op.f('ck_parcel_interests_ck_parcel_interests_interest_type')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'DISPUTED')", name=op.f('ck_parcel_interests_ck_parcel_interests_verification_status')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name=op.f('ck_parcel_interests_ck_parcel_interests_effective_dates')),
    sa.CheckConstraint('share_percentage IS NULL OR (share_percentage >= 0 AND share_percentage <= 100)', name=op.f('ck_parcel_interests_ck_parcel_interests_share_percentage')),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_parcel_interests_parcel_id_parcels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_holder_id'], ['right_holders.id'], name=op.f('fk_parcel_interests_right_holder_id_right_holders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcel_interests')),
    sa.UniqueConstraint('parcel_id', 'right_holder_id', 'interest_type', name='uq_parcel_interests_holder_type')
    )
    op.create_index('ix_parcel_interests_parcel_id', 'parcel_interests', ['parcel_id'], unique=False)
    op.create_index('ix_parcel_interests_right_holder_id', 'parcel_interests', ['right_holder_id'], unique=False)
    op.create_table('land_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_reference', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('required_area_sq_m', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN')", name=op.f('ck_land_requirements_ck_land_requirements_status')),
    sa.CheckConstraint('required_area_sq_m > 0', name=op.f('ck_land_requirements_ck_land_requirements_required_area_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_land_requirements_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_land_requirements')),
    sa.UniqueConstraint('project_id', 'requirement_reference', name='uq_land_requirements_project_reference')
    )
    op.create_index('ix_land_requirements_project_id', 'land_requirements', ['project_id'], unique=False)
    op.create_index('ix_land_requirements_status', 'land_requirements', ['status'], unique=False)
    op.create_table('acquisition_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('land_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(length=80), nullable=False),
    sa.Column('case_type', sa.String(length=30), server_default='STATUTORY', nullable=False),
    sa.Column('legal_route', sa.String(length=150), nullable=True),
    sa.Column('responsible_authority_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('current_stage', sa.String(length=40), server_default='PROPOSAL', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("case_type IN ('STATUTORY', 'NEGOTIATED', 'OTHER')", name=op.f('ck_acquisition_cases_ck_acquisition_cases_case_type')),
    sa.CheckConstraint("current_stage IN ('PROPOSAL', 'SCRUTINY', 'SIA', 'NOTIFICATION', 'SURVEY', 'OBJECTIONS', 'DECLARATION', 'CLAIMS_VERIFICATION', 'VALUATION', 'AWARD', 'COMPENSATION', 'R_AND_R', 'POSSESSION', 'HANDOVER', 'DISPUTE', 'CLOSURE')", name=op.f('ck_acquisition_cases_ck_acquisition_cases_current_stage')),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'ACTION_REQUIRED', 'APPROVED', 'REJECTED', 'COMPLETED')", name=op.f('ck_acquisition_cases_ck_acquisition_cases_status')),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_acquisition_cases_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['land_requirement_id'], ['land_requirements.id'], name=op.f('fk_acquisition_cases_land_requirement_id_land_requirements')),
    sa.ForeignKeyConstraint(['responsible_authority_id'], ['authorities.id'], name=op.f('fk_acquisition_cases_responsible_authority_id_authorities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition_cases')),
    sa.UniqueConstraint('case_number', name='uq_acquisition_cases_case_number')
    )
    op.create_index('ix_acquisition_cases_current_stage', 'acquisition_cases', ['current_stage'], unique=False)
    op.create_index('ix_acquisition_cases_land_requirement_id', 'acquisition_cases', ['land_requirement_id'], unique=False)
    op.create_index('ix_acquisition_cases_responsible_authority_id', 'acquisition_cases', ['responsible_authority_id'], unique=False)
    op.create_index('ix_acquisition_cases_status', 'acquisition_cases', ['status'], unique=False)
    op.create_table('acquisition_case_stage_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.String(length=40), nullable=True),
    sa.Column('to_stage', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_stage IS NULL OR from_stage IN ('PROPOSAL', 'SCRUTINY', 'SIA', 'NOTIFICATION', 'SURVEY', 'OBJECTIONS', 'DECLARATION', 'CLAIMS_VERIFICATION', 'VALUATION', 'AWARD', 'COMPENSATION', 'R_AND_R', 'POSSESSION', 'HANDOVER', 'DISPUTE', 'CLOSURE')", name=op.f('ck_acquisition_case_stage_history_ck_case_stage_history_from_stage')),
    sa.CheckConstraint("to_stage IN ('PROPOSAL', 'SCRUTINY', 'SIA', 'NOTIFICATION', 'SURVEY', 'OBJECTIONS', 'DECLARATION', 'CLAIMS_VERIFICATION', 'VALUATION', 'AWARD', 'COMPENSATION', 'R_AND_R', 'POSSESSION', 'HANDOVER', 'DISPUTE', 'CLOSURE')", name=op.f('ck_acquisition_case_stage_history_ck_case_stage_history_to_stage')),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], name=op.f('fk_acquisition_case_stage_history_acquisition_case_id_acquisition_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_acquisition_case_stage_history_changed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition_case_stage_history'))
    )
    op.create_index('ix_case_stage_history_case_id_changed_at', 'acquisition_case_stage_history', ['acquisition_case_id', 'changed_at'], unique=False)
    op.create_table('case_parcels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_area_sq_m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('inclusion_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('inclusion_reason', sa.Text(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inclusion_status IN ('ACTIVE', 'REMOVED')", name=op.f('ck_case_parcels_ck_case_parcels_inclusion_status')),
    sa.CheckConstraint('proposed_area_sq_m IS NULL OR proposed_area_sq_m > 0', name=op.f('ck_case_parcels_ck_case_parcels_proposed_area_positive')),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], name=op.f('fk_case_parcels_acquisition_case_id_acquisition_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_case_parcels_parcel_id_parcels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_parcels')),
    sa.UniqueConstraint('acquisition_case_id', 'parcel_id', name='uq_case_parcels_case_parcel')
    )
    op.create_index('ix_case_parcels_case_id', 'case_parcels', ['acquisition_case_id'], unique=False)
    op.create_index('ix_case_parcels_parcel_id', 'case_parcels', ['parcel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_parcels_parcel_id', table_name='case_parcels')
    op.drop_index('ix_case_parcels_case_id', table_name='case_parcels')
    op.drop_table('case_parcels')
    op.drop_index('ix_case_stage_history_case_id_changed_at', table_name='acquisition_case_stage_history')
    op.drop_table('acquisition_case_stage_history')
    op.drop_index('ix_acquisition_cases_status', table_name='acquisition_cases')
    op.drop_index('ix_acquisition_cases_responsible_authority_id', table_name='acquisition_cases')
    op.drop_index('ix_acquisition_cases_land_requirement_id', table_name='acquisition_cases')
    op.drop_index('ix_acquisition_cases_current_stage', table_name='acquisition_cases')
    op.drop_table('acquisition_cases')
    op.drop_index('ix_land_requirements_status', table_name='land_requirements')
    op.drop_index('ix_land_requirements_project_id', table_name='land_requirements')
    op.drop_table('land_requirements')
    op.drop_index('ix_parcel_interests_right_holder_id', table_name='parcel_interests')
    op.drop_index('ix_parcel_interests_parcel_id', table_name='parcel_interests')
    op.drop_table('parcel_interests')
    op.drop_index('ix_right_holders_external_reference', table_name='right_holders')
    op.drop_index('ix_right_holders_display_name', table_name='right_holders')
    op.drop_table('right_holders')
    op.drop_index('ix_parcels_survey_number', table_name='parcels')
    op.drop_index('ix_parcels_location', table_name='parcels')
    op.drop_table('parcels')
    # ### end Alembic commands ###
