"""Add land record retrieval provenance

Revision ID: 44aca6000e46
Revises: 3c19257a24eb
Create Date: 2026-09-26 19:04:09.365405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44aca6000e46'
down_revision: Union[str, Sequence[str], None] = '3c19257a24eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_record_retrievals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=150), nullable=False),
    sa.Column('source_record_reference', sa.String(length=200), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_version', sa.String(length=150), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED', 'SUCCESS', 'NO_RECORD', 'FAILED')", name=op.f('ck_land_record_retrievals_ck_land_record_retrievals_status')),
    sa.CheckConstraint('retrieved_at IS NULL OR retrieved_at >= requested_at', name=op.f('ck_land_record_retrievals_ck_land_record_retrievals_retrieved_after_requested')),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_land_record_retrievals_parcel_id_parcels'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_land_record_retrievals'))
    )
    op.create_index('ix_land_record_retrievals_parcel_id', 'land_record_retrievals', ['parcel_id'], unique=False)
    op.create_index('ix_land_record_retrievals_requested_at', 'land_record_retrievals', ['requested_at'], unique=False)
    op.create_index('ix_land_record_retrievals_source_record_reference', 'land_record_retrievals', ['source_record_reference'], unique=False)
    op.create_index('ix_land_record_retrievals_status', 'land_record_retrievals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_land_record_retrievals_status', table_name='land_record_retrievals')
    op.drop_index('ix_land_record_retrievals_source_record_reference', table_name='land_record_retrievals')
    op.drop_index('ix_land_record_retrievals_requested_at', table_name='land_record_retrievals')
    op.drop_index('ix_land_record_retrievals_parcel_id', table_name='land_record_retrievals')
    op.drop_table('land_record_retrievals')
    # ### end Alembic commands ###
