"""create projects table

Revision ID: 4a50637fa652
Revises: 4bf8e3e6cd45
Create Date: 2026-09-22 13:08:28.470536

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a50637fa652"
down_revision: Union[str, Sequence[str], None] = "4bf8e3e6cd45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("responsible_authority_id", sa.Uuid(), nullable=False),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_projects_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_authority_id"],
            ["authorities.id"],
            name=op.f("fk_projects_responsible_authority_id_authorities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_projects_updated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_projects"),
        ),
    )

    op.create_index(
        "ix_projects_authority_status",
        "projects",
        ["responsible_authority_id", "status"],
        unique=False,
    )

    op.create_index(
        op.f("ix_projects_code"),
        "projects",
        ["code"],
        unique=True,
    )

    op.create_index(
        op.f("ix_projects_created_by_user_id"),
        "projects",
        ["created_by_user_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_projects_responsible_authority_id"),
        "projects",
        ["responsible_authority_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_projects_status"),
        "projects",
        ["status"],
        unique=False,
    )

    op.create_index(
        op.f("ix_projects_updated_by_user_id"),
        "projects",
        ["updated_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_updated_by_user_id"),
        table_name="projects",
    )
    op.drop_index(
        op.f("ix_projects_status"),
        table_name="projects",
    )
    op.drop_index(
        op.f("ix_projects_responsible_authority_id"),
        table_name="projects",
    )
    op.drop_index(
        op.f("ix_projects_created_by_user_id"),
        table_name="projects",
    )
    op.drop_index(
        op.f("ix_projects_code"),
        table_name="projects",
    )
    op.drop_index(
        "ix_projects_authority_status",
        table_name="projects",
    )
    op.drop_table("projects")
    # ### end Alembic commands ###