"""add departments authorities and user organization

Revision ID: cbfc8ea26725
Revises: 41252a35472d
Create Date: 2026-09-18 22:07:47.692113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfc8ea26725'
down_revision: Union[str, Sequence[str], None] = '41252a35472d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('authorities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('authority_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_authorities_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authorities'))
    )
    op.create_index(op.f('ix_authorities_code'), 'authorities', ['code'], unique=True)
    op.create_index(op.f('ix_authorities_department_id'), 'authorities', ['department_id'], unique=False)
    op.add_column('users', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('authority_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_authority_id'), 'users', ['authority_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_authority_id_authorities'), 'users', 'authorities', ['authority_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_users_department_id_departments'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_department_id_departments'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_authority_id_authorities'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_users_authority_id'), table_name='users')
    op.drop_column('users', 'authority_id')
    op.drop_column('users', 'department_id')
    op.drop_index(op.f('ix_authorities_department_id'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_code'), table_name='authorities')
    op.drop_table('authorities')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
